# This is used by Travis CI site in order
# to build and test the library online.

language: cpp

before_install:
  - pip install --user cpp-coveralls

env:
  global:
    - COVERAGE="--coverage"
  matrix:
    - BUILD_DIR="apps/"
    - BUILD_DIR="apps/ACvsBC/"
    - BUILD_DIR="apps/CELAR/"
    - BUILD_DIR="apps/ITC/"
    - BUILD_DIR="apps/hadoop/"

script:
    - echo "$(nproc) available cores"
    - cd $BUILD_DIR && make -j $((2 * $(nproc))) && make test && cd -

after_success:
  - coveralls -b $BUILD_DIR
