# This is used by Travis CI site in order
# to build and test the library online.

language: cpp

before_install:
  - pip install --user cpp-coveralls

env:
  global:
    - COVERAGE="--coverage"
  matrix:
    - BUILD_DIR="apps/ITC/"

script: cd $BUILD_DIR && make && make test && cd -

after_success:
  - coveralls -b $BUILD_DIR
