# This is used by Travis CI site in order
# to build and test the library online.

language: cpp

env:
  global:
    - COVERAGE="--coverage"

matrix:
  include:
    - env: DIRECTORY="apps/"
      addons:
        apt:
          packages:
            - valgrind

    - env: DIRECTORY="apps/for_amorgos/"

    - env: DIRECTORY="apps/XCSP3/"
           TARGET="naxos-xcsp3"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
          packages:
            - g++-7
            - valgrind
            - clang-format-5.0
      before_script:
        - CXX=g++-7
        - $CXX --version

    - env: DIRECTORY="apps/CELAR/"
           DATASET="SCEN06"
      addons:
        apt:
          packages:
            - valgrind
    - env: DIRECTORY="apps/CELAR/"
           DATASET="SCEN07"
    - env: DIRECTORY="apps/CELAR/"
           DATASET="SCEN08"
    - env: DIRECTORY="apps/CELAR/"
           DATASET="SCEN09"
    - env: DIRECTORY="apps/CELAR/"
           DATASET="SCEN10"

    - env: DIRECTORY="apps/Hadoop/"

    - env: DIRECTORY="apps/ITC/"
           DATASET="comp01.ctt"
           METHOD="DFS"
      addons:
        apt:
          packages:
            - valgrind
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp02.ctt"
           METHOD="LDS"
      addons:
        apt:
          packages:
            - valgrind
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp03.ctt"
           METHOD="IBROAD"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp04.ctt"
           METHOD="PoPS"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp05.ctt"
           METHOD="DBS"
      addons:
        apt:
          packages:
            - valgrind
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp06.ctt"
           METHOD="CREDIT 100"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp07.ctt"
           METHOD="LAN 20"
           METHOD_LOCAL_SEARCH="DBDS"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp08.ctt"
           METHOD="BBS 100"
           METHOD_LOCAL_SEARCH="DFS RANDOM_VAR_HEUR"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp09.ctt"
           METHOD="RDFS 100 1000"
           METHOD_LOCAL_SEARCH="DFS RANDOM_VAL_HEUR"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp10.ctt"
           METHOD="GNS"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp11.ctt"
           METHOD="FNS fSample"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp12.ctt"
           METHOD="FNS fSampleMiddle"
           METHOD_LOCAL_SEARCH="FNS fSampleExp"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp13.ctt"
           METHOD="ISAMP 1000"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp14.ctt"
           METHOD="ONESAMP"

script:
    - cd $DIRECTORY
    - cmake .
    - make -j $TARGET
    - ctest -V
    - cd -
