# This is used by Travis CI site in order
# to build and test the library online.

language: cpp

before_install:
  - pip install --user cpp-coveralls

env:
  global:
    - COVERAGE="--coverage"
  matrix:
    - DIRECTORY="apps/"
    - DIRECTORY="apps/ACvsBC/"
    - DIRECTORY="apps/CELAR/"
    - DIRECTORY="apps/ITC/"
      METHOD="DFS"
      DATASET="comp01.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="LDS"
      DATASET="comp02.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="IBROAD"
      DATASET="comp03.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="PoPS"
      DATASET="comp04.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="DBS"
      DATASET="comp05.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="CREDIT 100"
      DATASET="comp06.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="LAN 20"
      METHOD_LOCAL_SEARCH="DBDS"
      DATASET="comp07.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="BBS 100"
      METHOD_LOCAL_SEARCH="DFS RANDOM_VAR_HEUR"
      DATASET="comp08.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="RDFS 100 1000"
      METHOD_LOCAL_SEARCH="DFS RANDOM_VAL_HEUR"
      DATASET="comp09.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="GNS"
      METHOD_LOCAL_SEARCH="DOMAIN_SPLITTING"
      DATASET="comp10.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="FNS fSample"
      METHOD_LOCAL_SEARCH="DOMAIN_SPLITTING FAIR"
      DATASET="comp11.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="FNS fSampleMiddle"
      METHOD_LOCAL_SEARCH="FNS fSampleExp"
      DATASET="comp12.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="ISAMP 1000"
      DATASET="comp13.ctt"
    - DIRECTORY="apps/ITC/"
      METHOD="ONESAMP"
      DATASET="comp14.ctt"
    - DIRECTORY="apps/hadoop/"

script:
    - cd $DIRECTORY
    - make -j
    - make test
    - cd -

after_success:
  - coveralls -b $DIRECTORY
