# This is used by Travis CI site in order
# to build and test the library online.

language: cpp

before_install:
  - pip install --user cpp-coveralls

env:
  global:
    - COVERAGE="--coverage"

matrix:
  include:
    - env: DIRECTORY="apps/"

    - env: DIRECTORY="apps/XCSP3/"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      before_script:
        - sed -i 's/g++/g++-4.9/' $DIRECTORY/{Makefile,XCSP3-CPP-Parser/samples/makefile}

    - env: DIRECTORY="apps/ACvsBC/"
      addons:
        apt:
          packages:
            - time
            - gnuplot

    - env: DIRECTORY="apps/CELAR/"
           DATASET="SCEN06"
    - env: DIRECTORY="apps/CELAR/"
           DATASET="SCEN07"
    - env: DIRECTORY="apps/CELAR/"
           DATASET="SCEN08"
    - env: DIRECTORY="apps/CELAR/"
           DATASET="SCEN09"
    - env: DIRECTORY="apps/CELAR/"
           DATASET="SCEN10"

    - env: DIRECTORY="apps/ITC/"
           DATASET="comp01.ctt"
           METHOD="DFS"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp02.ctt"
           METHOD="LDS"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp03.ctt"
           METHOD="IBROAD"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp04.ctt"
           METHOD="PoPS"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp05.ctt"
           METHOD="DBS"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp06.ctt"
           METHOD="CREDIT 100"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp07.ctt"
           METHOD="LAN 20"
           METHOD_LOCAL_SEARCH="DBDS"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp08.ctt"
           METHOD="BBS 100"
           METHOD_LOCAL_SEARCH="DFS RANDOM_VAR_HEUR"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp09.ctt"
           METHOD="RDFS 100 1000"
           METHOD_LOCAL_SEARCH="DFS RANDOM_VAL_HEUR"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp10.ctt"
           METHOD="GNS"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp11.ctt"
           METHOD="FNS fSample"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp12.ctt"
           METHOD="FNS fSampleMiddle"
           METHOD_LOCAL_SEARCH="FNS fSampleExp"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp13.ctt"
           METHOD="ISAMP 1000"
    - env: DIRECTORY="apps/ITC/"
           DATASET="comp14.ctt"
           METHOD="ONESAMP"

    - env: DIRECTORY="apps/hadoop/"

    - env: DIRECTORY="amorgos/apps/"

script:
    - cd $DIRECTORY
    - make -j
    - make test
    - cd -

after_success:
  - coveralls -b $DIRECTORY
