# This is used by Travis CI site in order
# to build and test the library online.

language: cpp

before_install:
  - pip install --user cpp-coveralls

env:
  global:
    - COVERAGE="--coverage"
  matrix:
    - BUILD_DIR="apps/"
    - BUILD_DIR="apps/ACvsBC/"
    - BUILD_DIR="apps/CELAR/"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="DFS"
      DATASET="comp01.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="LDS"
      DATASET="comp02.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="IBROAD"
      DATASET="comp03.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="PoPS"
      DATASET="comp04.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="DBS"
      DATASET="comp05.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="DFS"
      DATASET="comp06.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="DBS"
      DATASET="comp07.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="DFS"
      DATASET="comp08.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="DFS"
      DATASET="comp09.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="DFS"
      DATASET="comp10.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="DFS"
      DATASET="comp11.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="DFS"
      DATASET="comp12.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="DFS"
      DATASET="comp13.ctt"
    - BUILD_DIR="apps/ITC/"
      SEARCH_METHOD="DFS"
      DATASET="comp14.ctt"
    - BUILD_DIR="apps/hadoop/"

script:
    - cd $BUILD_DIR
    - make -j
    - make test
    - cd -

after_success:
  - coveralls -b $BUILD_DIR
