# This is used by Travis CI site in order
# to build and test the library online.

language: cpp

before_install:
  - pip install cpp-coveralls

env:
  global:
    - COVERAGE="--coverage"
  matrix:
    - BUILD_DIR="core/bounds-consistency/"
    - BUILD_DIR="apps/"
    - BUILD_DIR="apps/ITC/"
    - BUILD_DIR="apps/CELAR/"
    - BUILD_DIR="apps/hadoop/"

script: cd $BUILD_DIR && make && make test && cd -

after_success:
  - coveralls -r $BUILD_DIR
